#This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Develop S3 & CodeDeploy CI/CD

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: make application-testDB.properties
        run:  touch ./src/main/resources/application-testDB.properties
        shell: bash

      - name: deliver application-testDB.properties
        run: echo "${{ secrets.DEVELOP_PROPERTIES }}" > ./src/main/resources/application-testDB.properties
        shell: bash

      - name: make application.properties
        run:  touch ./src/main/resources/application.properties
        shell: bash

      - name: deliver application.properties
        run: echo "${{ secrets.DEVELOP_APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties
        shell: bash

      - name: test make application.properties
        run: |
          mkdir -p ./src/test/resources
          touch ./src/test/resources/application.properties
        shell: bash

      - name: test deliver application.properties
        run: echo "${{ secrets.TEST_PROPERTIES }}" > ./src/test/resources/application.properties
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle Build ìˆ˜í–‰
          # uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        # with:
        # arguments: build
        run : ./gradlew clean build --info
        shell: bash

      - name: í…ŒìŠ¤íŠ¸ ê²°ê³¼ë¥¼ PRì— ì½”ë©˜íŠ¸ë¡œ ë“±ë¡í•©ë‹ˆë‹¤
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'

      - name: í…ŒìŠ¤íŠ¸ ì‹¤íŒ¨ ì‹œ, ì‹¤íŒ¨í•œ ì½”ë“œ ë¼ì¸ì— Check ì½”ë©˜íŠ¸ë¥¼ ë“±ë¡í•©ë‹ˆë‹¤
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ github.token }}

      - name: í…ŒìŠ¤íŠ¸ ì»¤ë²„ë¦¬ì§€ë¥¼ PRì— ì½”ë©˜íŠ¸ë¡œ ë“±ë¡í•©ë‹ˆë‹¤
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          title: ğŸ“ í…ŒìŠ¤íŠ¸ ì»¤ë²„ë¦¬ì§€ ë¦¬í¬íŠ¸ì…ë‹ˆë‹¤
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 50

      - name: build ì‹¤íŒ¨ ì‹œ Slackìœ¼ë¡œ ì•Œë¦½ë‹ˆë‹¤
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: ë°±ì—”ë“œ ë¹Œë“œ ì‹¤íŒ¨ ì•Œë¦¼
          fields: repo, message, commit, author, action, eventName, ref, workflow, job, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

      # ë””ë ‰í† ë¦¬ ìƒì„±
      - name: Make Directory
        run: mkdir -p deploy

      # Jar íŒŒì¼ ë³µì‚¬
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy

      # appspec.yml íŒŒì¼ ë³µì‚¬
      - name: Copy appspec.yml
        run: cp appspec.yml ./deploy


      # script files ë³µì‚¬
      - name: Copy script
        run: cp ./scripts/*.sh ./deploy

      - name: Make zip file
        run: zip -r ./cicdtest.zip ./deploy
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEVELOP_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEVELOP_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./cicdtest.zip s3://yogiyoclone/



      # Deploy
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEVELOP_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEVELOP_AWS_SECRET_ACCESS_KEY }}
        run: aws deploy create-deployment --application-name ci_cd_deploy
          --deployment-group-name ci_cd_deploy
          --file-exists-behavior OVERWRITE
          --s3-location bucket=yogiyoclone,bundleType=zip,key=cicdtest.zip
          --region ap-northeast-2